/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 iphone_13_pro.glb
Author: SDC PERFORMANCE™️ (https://sketchfab.com/3Duae)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-iphone-13-pro-2021-a35156d91cf44e70a2fdfeade54ae0b2
Title: (FREE) iPhone 13 Pro 2021
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('./models/iphone_13_pro.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 1.45, 0]} scale={0.04}>
        <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Black} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Back} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.GOLD} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.BARRES} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Labber} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.GLASS} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.Lenscover} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.Display} />
        {/* <mesh geometry={nodes.Object_13.geometry}>
          <meshStandardMaterial color={"#ff0000"}/>
        </mesh> */}
        <mesh geometry={nodes.Object_14.geometry} material={materials['Lens.2']} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.material_11} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/iphone_13_pro.glb')
