/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 kuma_heavy_robot_r-9000s.glb --transform --simplify
Author: Heinrich (https://sketchfab.com/Gevalt)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/kuma-heavy-robot-r-9000s-8b77bdbe705f4e9697790fd404da49a9
Title: KUMA Heavy Robot R-9000S
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/kuma_heavy_robot_r-9000s-transformed.glb')
  const { actions } = useAnimations(animations, group)

  // Start animation
  useEffect(() => {
    actions.Track.play()
  })

  return (
    <group ref={group} {...props} dispose={null} scale={0.003}>
      <group name="Armature" position={[-866.65, 1714.41, 8.21]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <primitive object={nodes._rootJoint} />
        <skinnedMesh name="skin" castShadow receiveShadow geometry={nodes.Object_19.geometry} material={materials['Material.002']} skeleton={nodes.Object_19.skeleton} />
        {/* <skinnedMesh name="outline" geometry={nodes.Object_21.geometry} material={materials['Material.001']} skeleton={nodes.Object_21.skeleton} /> */}
      </group>
    </group>
  )
}

// useGLTF.preload('./models/kuma_heavy_robot_r-9000s-transformed.glb')
